name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa uma vez por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repos
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: andressa-limas
          outputs: dist

      - name: Push animation to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          force: true
          path: dist
